name: Check Markdown Spelling

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Spell Checker
        run: npm install -g markdown-spellcheck

      - name: Find Markdown Files
        id: find_files
        run: |
          files=$(find . -type f -name '*.md')
          echo "::set-output name=files::$files"

      - name: Run Spell Checker
        if: steps.find_files.outputs.files != ''
        run: mdspell --en-us --report ${{ steps.find_files.outputs.files }} > result.txt || true

      - name: Check for Spelling Errors
        id: check_errors
        run: |
          if [ -s result.txt ]; then
            echo "::set-output name=errors::true"
          else
            echo "::set-output name=errors::false"
          fi

      - name: Log Spelling Errors
        if: steps.check_errors.outputs.errors == 'true'
        run: |
          echo "Spelling errors found:"
          cat result.txt
